# Generated by Django 4.2.6 on 2023-11-01 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='les_count',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='количество уроков'),
        ),
    ]
